name = "TaylorInterface"
uuid = "628e9319-2ed5-413a-8fcb-ba6034deb837"
authors = ["Alseidon <alexandre.prieur@obspm.fr> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
